package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CdmsSubmissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCdmsSubmissionAllPropertiesEquals(CdmsSubmission expected, CdmsSubmission actual) {
        assertCdmsSubmissionAutoGeneratedPropertiesEquals(expected, actual);
        assertCdmsSubmissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCdmsSubmissionAllUpdatablePropertiesEquals(CdmsSubmission expected, CdmsSubmission actual) {
        assertCdmsSubmissionUpdatableFieldsEquals(expected, actual);
        assertCdmsSubmissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCdmsSubmissionAutoGeneratedPropertiesEquals(CdmsSubmission expected, CdmsSubmission actual) {
        assertThat(actual)
            .as("Verify CdmsSubmission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCdmsSubmissionUpdatableFieldsEquals(CdmsSubmission expected, CdmsSubmission actual) {
        assertThat(actual)
            .as("Verify CdmsSubmission relevant properties")
            .satisfies(a -> assertThat(a.getSubmissionRef()).as("check submissionRef").isEqualTo(expected.getSubmissionRef()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getResponseCode()).as("check responseCode").isEqualTo(expected.getResponseCode()))
            .satisfies(a -> assertThat(a.getResponseMessage()).as("check responseMessage").isEqualTo(expected.getResponseMessage()))
            .satisfies(a -> assertThat(a.getAttempts()).as("check attempts").isEqualTo(expected.getAttempts()))
            .satisfies(a -> assertThat(a.getSubmittedAt()).as("check submittedAt").isEqualTo(expected.getSubmittedAt()))
            .satisfies(a -> assertThat(a.getLastAttemptAt()).as("check lastAttemptAt").isEqualTo(expected.getLastAttemptAt()))
            .satisfies(a -> assertThat(a.getNextRetryAt()).as("check nextRetryAt").isEqualTo(expected.getNextRetryAt()))
            .satisfies(a -> assertThat(a.getCdmsCustomerId()).as("check cdmsCustomerId").isEqualTo(expected.getCdmsCustomerId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCdmsSubmissionUpdatableRelationshipsEquals(CdmsSubmission expected, CdmsSubmission actual) {
        // empty method
    }
}
