package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerIdentifierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerIdentifierAllPropertiesEquals(CustomerIdentifier expected, CustomerIdentifier actual) {
        assertCustomerIdentifierAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerIdentifierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerIdentifierAllUpdatablePropertiesEquals(CustomerIdentifier expected, CustomerIdentifier actual) {
        assertCustomerIdentifierUpdatableFieldsEquals(expected, actual);
        assertCustomerIdentifierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerIdentifierAutoGeneratedPropertiesEquals(CustomerIdentifier expected, CustomerIdentifier actual) {
        assertThat(actual)
            .as("Verify CustomerIdentifier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerIdentifierUpdatableFieldsEquals(CustomerIdentifier expected, CustomerIdentifier actual) {
        assertThat(actual)
            .as("Verify CustomerIdentifier relevant properties")
            .satisfies(a -> assertThat(a.getIdentifierType()).as("check identifierType").isEqualTo(expected.getIdentifierType()))
            .satisfies(a -> assertThat(a.getIdentifierValue()).as("check identifierValue").isEqualTo(expected.getIdentifierValue()))
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()))
            .satisfies(a -> assertThat(a.getIsPrimary()).as("check isPrimary").isEqualTo(expected.getIsPrimary()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getVerifiedAt()).as("check verifiedAt").isEqualTo(expected.getVerifiedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerIdentifierUpdatableRelationshipsEquals(CustomerIdentifier expected, CustomerIdentifier actual) {
        assertThat(actual)
            .as("Verify CustomerIdentifier relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
