package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KycConsentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycConsentAllPropertiesEquals(KycConsent expected, KycConsent actual) {
        assertKycConsentAutoGeneratedPropertiesEquals(expected, actual);
        assertKycConsentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycConsentAllUpdatablePropertiesEquals(KycConsent expected, KycConsent actual) {
        assertKycConsentUpdatableFieldsEquals(expected, actual);
        assertKycConsentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycConsentAutoGeneratedPropertiesEquals(KycConsent expected, KycConsent actual) {
        assertThat(actual)
            .as("Verify KycConsent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycConsentUpdatableFieldsEquals(KycConsent expected, KycConsent actual) {
        assertThat(actual)
            .as("Verify KycConsent relevant properties")
            .satisfies(a -> assertThat(a.getConsentText()).as("check consentText").isEqualTo(expected.getConsentText()))
            .satisfies(a -> assertThat(a.getConsented()).as("check consented").isEqualTo(expected.getConsented()))
            .satisfies(a -> assertThat(a.getConsentedAt()).as("check consentedAt").isEqualTo(expected.getConsentedAt()))
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getConsentVersion()).as("check consentVersion").isEqualTo(expected.getConsentVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycConsentUpdatableRelationshipsEquals(KycConsent expected, KycConsent actual) {
        // empty method
    }
}
