package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KycCaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycCaseAllPropertiesEquals(KycCase expected, KycCase actual) {
        assertKycCaseAutoGeneratedPropertiesEquals(expected, actual);
        assertKycCaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycCaseAllUpdatablePropertiesEquals(KycCase expected, KycCase actual) {
        assertKycCaseUpdatableFieldsEquals(expected, actual);
        assertKycCaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycCaseAutoGeneratedPropertiesEquals(KycCase expected, KycCase actual) {
        assertThat(actual)
            .as("Verify KycCase auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycCaseUpdatableFieldsEquals(KycCase expected, KycCase actual) {
        assertThat(actual)
            .as("Verify KycCase relevant properties")
            .satisfies(a -> assertThat(a.getKycRef()).as("check kycRef").isEqualTo(expected.getKycRef()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getLastActivityAt()).as("check lastActivityAt").isEqualTo(expected.getLastActivityAt()))
            .satisfies(a -> assertThat(a.getLastUpdatedAt()).as("check lastUpdatedAt").isEqualTo(expected.getLastUpdatedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getValidationErrors()).as("check validationErrors").isEqualTo(expected.getValidationErrors()))
            .satisfies(a -> assertThat(a.getInternalNotes()).as("check internalNotes").isEqualTo(expected.getInternalNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycCaseUpdatableRelationshipsEquals(KycCase expected, KycCase actual) {
        assertThat(actual)
            .as("Verify KycCase relationships")
            .satisfies(a -> assertThat(a.getConsent()).as("check consent").isEqualTo(expected.getConsent()))
            .satisfies(a -> assertThat(a.getSubmission()).as("check submission").isEqualTo(expected.getSubmission()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
