package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KycDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycDocumentAllPropertiesEquals(KycDocument expected, KycDocument actual) {
        assertKycDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertKycDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycDocumentAllUpdatablePropertiesEquals(KycDocument expected, KycDocument actual) {
        assertKycDocumentUpdatableFieldsEquals(expected, actual);
        assertKycDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycDocumentAutoGeneratedPropertiesEquals(KycDocument expected, KycDocument actual) {
        assertThat(actual)
            .as("Verify KycDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycDocumentUpdatableFieldsEquals(KycDocument expected, KycDocument actual) {
        assertThat(actual)
            .as("Verify KycDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getStoragePath()).as("check storagePath").isEqualTo(expected.getStoragePath()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getUploadedAt()).as("check uploadedAt").isEqualTo(expected.getUploadedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getChecksum()).as("check checksum").isEqualTo(expected.getChecksum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycDocumentUpdatableRelationshipsEquals(KycDocument expected, KycDocument actual) {
        assertThat(actual)
            .as("Verify KycDocument relationships")
            .satisfies(a -> assertThat(a.getKycCase()).as("check kycCase").isEqualTo(expected.getKycCase()));
    }
}
