package zw.co.fgr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KycNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycNotificationAllPropertiesEquals(KycNotification expected, KycNotification actual) {
        assertKycNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertKycNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycNotificationAllUpdatablePropertiesEquals(KycNotification expected, KycNotification actual) {
        assertKycNotificationUpdatableFieldsEquals(expected, actual);
        assertKycNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycNotificationAutoGeneratedPropertiesEquals(KycNotification expected, KycNotification actual) {
        assertThat(actual)
            .as("Verify KycNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycNotificationUpdatableFieldsEquals(KycNotification expected, KycNotification actual) {
        assertThat(actual)
            .as("Verify KycNotification relevant properties")
            .satisfies(a -> assertThat(a.getNotificationType()).as("check notificationType").isEqualTo(expected.getNotificationType()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()))
            .satisfies(a -> assertThat(a.getDelivered()).as("check delivered").isEqualTo(expected.getDelivered()))
            .satisfies(a -> assertThat(a.getDeliveredAt()).as("check deliveredAt").isEqualTo(expected.getDeliveredAt()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKycNotificationUpdatableRelationshipsEquals(KycNotification expected, KycNotification actual) {
        assertThat(actual)
            .as("Verify KycNotification relationships")
            .satisfies(a -> assertThat(a.getKycCase()).as("check kycCase").isEqualTo(expected.getKycCase()));
    }
}
