export enum DocumentType {
  NATIONAL_ID = 'NATIONAL_ID',

  PASSPORT = 'PASSPORT',

  COMPANY_REGISTRATION = 'COMPANY_REGISTRATION',

  MINE_LICENSE = 'MINE_LICENSE',

  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',

  SELFIE = 'SELFIE',

  OTHER = 'OTHER',
}
