export enum NotificationType {
  WELCOME = 'WELCOME',

  DOCUMENT_RECEIVED = 'DOCUMENT_RECEIVED',

  SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS',

  SUBMISSION_FAILED = 'SUBMISSION_FAILED',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  TIMEOUT_WARNING = 'TIMEOUT_WARNING',

  HELP_REQUEST = 'HELP_REQUEST',
}
